os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

before_install:
 - curl -sL https://ibm.biz/idt-installer | bash
 - ibmcloud login --apikey ${BX_API_KEY} -r ${BX_REGION}
 - ibmcloud cr login
 - docker pull ${CR_CI}/sysporter:deps || true
 - docker pull ${CR_CI}/sysporter:builder || true
 - docker pull ${CR_CI}/sysporter:runtime || true
 - docker pull ${CR_CI}/sysporter:testing || true

script:
 - make -C modules init
 - docker build --cache-from ${CR_CI}/sysporter:deps --target deps -t ${CR_CI}/sysporter:deps .
 - docker build --build-arg TRAVIS_BUILD_NUMBER --cache-from ${CR_CI}/sysporter:deps --cache-from ${CR_CI}/sysporter:builder --target builder -t ${CR_CI}/sysporter:builder .
 - docker build --cache-from ${CR_CI}/sysporter:deps --cache-from ${CR_CI}/sysporter:builder --cache-from ${CR_CI}/sysporter:runtime --target runtime -t ${CR_CI}/sysporter:runtime .
 - docker build --cache-from ${CR_CI}/sysporter:deps --cache-from ${CR_CI}/sysporter:builder --cache-from ${CR_CI}/sysporter:runtime --cache-from ${CR_CI}/sysporter:testing --target testing -t ${CR_CI}/sysporter:testing .
 - docker run --rm --name sftests -it -v "$(pwd)/tests:/usr/local/sysflow/tests" -e quiet=true ${CR_CI}/sysporter:testing -t tests/tests.bats

after_success:
 - docker push ${CR_CI}/sysporter:deps 
 - docker push ${CR_CI}/sysporter:builder 
 - docker push ${CR_CI}/sysporter:runtime
 - docker push ${CR_CI}/sysporter:testing

branches:
  only:
  - /.*/

notifications:
  email: true
