os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

before_install:
 - curl -sL https://ibm.biz/idt-installer | bash
 - ibmcloud plugin install container-registry -r Bluemix
 - ibmcloud login --apikey ${BX_API_KEY} -r ${BX_REGION}
 - ibmcloud cr login
 - docker pull ${CR_CI}/sysporter:deps || true
 - docker pull ${CR_CI}/sysporter:builder || true
 - docker pull ${CR_CI}/sysporter:runtime || true
 - docker pull ${CR_CI}/sysporter:testing || true

script:
 - make -C src/modules init
 - docker build --cache-from sysporter:deps --target deps -t sysporter:deps .
 - docker build --cache-from sysporter:deps --cache-from sysporter:builder --target builder -t sysporter:builder .
 - docker build --cache-from sysporter:deps --cache-from sysporter:builder --cache-from sysporter:runtime --target runtime -t sysporter:runtime .
 - docker build --cache-from sysporter:deps --cache-from sysporter:builder --cache-from sysporter:runtime --cache-from sysporter:testing --target testing -t sysporter:testing .
 - docker run --name sf -it sysporter:testing /bin/hostname
 - docker rm sf

after_success:
 - docker tag sysporter:deps ${CR_CI}/sysporter:deps && docker push ${CR_CI}/sysporter:deps 
 - docker tag sysporter:builder ${CR_CI}/sysporter:builder && docker push ${CR_CI}/sysporter:builder 
 - docker tag sysporter:runtime ${CR_CI}/sysporter:runtime && docker push ${CR_CI}/sysporter:runtime
 - docker tag sysporter:testing ${CR_CI}/sysporter:testing && docker push ${CR_CI}/sysporter:testing

branches:
  only:
  - master

notifications:
  email: true
