os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

before_install:
 - curl -sL https://ibm.biz/idt-installer | bash
 - ibmcloud login --apikey ${BX_API_KEY} -r ${BX_REGION}
 - ibmcloud cr login
 - echo "${TRAVIS_BRANCH}"
 - echo "$TRAVIS_BRANCH"
 - echo ${TRAVIS_BRANCH}
 - docker pull ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} || true
 - docker pull ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} || true
 - docker pull ${CR_CI}/sysporter:runtime.${TRAVIS_BRANCH} || true
 - docker pull ${CR_CI}/sysporter:testing.${TRAVIS_BRANCH} || true

script:
 - make -C modules init
 - docker build --cache-from ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} --target deps -t ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} .
 - docker build --build-arg ${TRAVIS_BUILD_NUMBER} --cache-from ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} --target builder -t ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} .
 - docker build --cache-from ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:runtime.${TRAVIS_BRANCH} --target runtime -t ${CR_CI}/sysporter:runtime.${TRAVIS_BRANCH} .
 - docker build --cache-from ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:runtime.${TRAVIS_BRANCH} --cache-from ${CR_CI}/sysporter:testing.${TRAVIS_BRANCH} --target testing -t ${CR_CI}/sysporter:testing.${TRAVIS_BRANCH} .
 - docker run --rm --name sftests -it -v "$(pwd)/tests:/usr/local/sysflow/tests" -e quiet=true ${CR_CI}/sysporter:testing.${TRAVIS_BRANCH} -t tests/tests.bats

after_success:
 - docker push ${CR_CI}/sysporter:deps.${TRAVIS_BRANCH} 
 - docker push ${CR_CI}/sysporter:builder.${TRAVIS_BRANCH} 
 - docker push ${CR_CI}/sysporter:runtime.${TRAVIS_BRANCH}
 - docker push ${CR_CI}/sysporter:testing.${TRAVIS_BRANCH}

branches:
  only:
  - /.*/

notifications:
  email: true
